# Generated by Django 5.1.5 on 2025-07-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_best_products_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimg',
            options={'verbose_name': 'Carousel Image', 'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.RemoveField(
            model_name='carouselimg',
            name='order',
        ),
    ]
