# Generated by Django 5.0.14 on 2025-12-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tag_slug'),
    ]

    operations = [
    ]
