# Generated by Django 5.1.5 on 2025-07-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_carouselimg_options_remove_carouselimg_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimg',
            options={'ordering': ['order'], 'verbose_name': 'Carousel Image', 'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.AddField(
            model_name='carouselimg',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
