# Generated by Django 5.1.5 on 2025-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_carouselimg_options_carouselimg_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimg',
            name='order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
