# Generated by Django 5.1.5 on 2025-07-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_services_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
