# Generated by Django 5.1.5 on 2025-07-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_services_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='img',
            new_name='image',
        ),
    ]
