# Generated by Django 5.1.5 on 2025-07-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Upload product image (recommended ratio: 4:3, width > height, min 800x600px)', upload_to='products/'),
        ),
    ]
