# Generated by Django 5.0.3 on 2026-07-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_platformsettings_remove_product_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_payout",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
