# Generated by Django 5.1.5 on 2025-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Service image (minimum 1280x720px, 16:9 ratio preferred, width ≥ height)', upload_to='services/'),
        ),
    ]
