# Generated by Django 5.1.5 on 2025-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Upload service image (width must be equal to or greater than height)', upload_to='services/'),
        ),
    ]
