# Generated by Django 5.0.3 on 2026-08-18 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_order_delivery_type_order_discount_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paymob", "Paymob"),
                    ("fawry", "Fawry"),
                    ("cash", "Cash on Delivery"),
                ],
                default="stripe",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_payment_id",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_response",
            field=models.JSONField(
                blank=True, help_text="Raw response from payment provider", null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="EGP", max_length=10),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["provider_payment_id"], name="api_payment_provide_b3ab49_idx"
            ),
        ),
    ]
