# Generated by Django 5.1.5 on 2025-07-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(help_text='Upload contact icon (square or width ≥ height recommended)', upload_to='contact/')),
                ('name', models.CharField(help_text='Contact name or title', max_length=100)),
                ('value', models.CharField(help_text='Contact information (phone, email, address, etc.)', max_length=200)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('address', 'Address'), ('social', 'Social Media'), ('other', 'Other')], default='other', help_text='Type of contact information', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which contacts should be displayed')),
                ('is_active', models.BooleanField(default=True, help_text='Is this contact information currently active?')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
