# Generated by Django 5.0.3 on 2026-08-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_payment_method_payment_provider_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="paymob_account_id",
            field=models.CharField(
                blank=True,
                help_text="Paymob merchant/sub-merchant account ID for payouts.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="paymob_wallet_number",
            field=models.CharField(
                blank=True,
                help_text="Mobile wallet number registered with Paymob.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paymob", "Paymob"),
                    ("fawry", "Fawry"),
                ],
                default="stripe",
                max_length=16,
            ),
        ),
    ]
