# Generated by Django 5.1.5 on 2025-07-29 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_contact_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category', verbose_name='Product Category'),
        ),
    ]
