# Generated by Django 5.0.3 on 2026-08-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_productcomment_productlike_sellerfollower"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional promotional video (MP4/WebM) shown in the Shorts feed.",
                upload_to="products/videos/",
            ),
        ),
    ]
