# Generated by Django 5.1.5 on 2025-07-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carouselimg',
            old_name='img',
            new_name='image',
        ),
    ]
