# Generated by Django 5.0.3 on 2026-09-01 09:41

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_product_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Optional promotional video (MP4/WebM) shown in the Shorts feed.",
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    resource_type="video"
                ),
                upload_to="products/videos/",
            ),
        ),
    ]
