# Generated by Django 5.1.5 on 2025-08-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_img_carouselimg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Upload product image (width must be equal to or greater than height)', upload_to='products/'),
        ),
    ]
