# Generated by Django 5.0.3 on 2026-09-01 10:17

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_product_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True, max_length=400)),
                (
                    "video",
                    models.FileField(
                        help_text="Promotional/brand advertisement video shown in the Shorts feed (MP4/WebM).",
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                            resource_type="video"
                        ),
                        upload_to="ads/videos/",
                    ),
                ),
                ("poster", models.ImageField(blank=True, upload_to="ads/posters/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_videos",
                        to="api.sellerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertisement Video",
                "verbose_name_plural": "Advertisement Videos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        help_text="Optional gallery video for this product (MP4/WebM).",
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                            resource_type="video"
                        ),
                        upload_to="products/gallery/videos/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product gallery video (shown alongside gallery images).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_videos",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Video",
                "verbose_name_plural": "Product Videos",
                "ordering": ["created_at"],
            },
        ),
    ]
