# Generated by Django 5.1.5 on 2025-08-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
