# Generated by Django 5.1.5 on 2025-08-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
