"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv
import os

load_dotenv()



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "t")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS" , "").split(",")


# Application definition

INSTALLED_APPS = [
    # 'jazzmin', 
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist', 
    'rest_framework_simplejwt',
    "rest_framework",
    "corsheaders",
    "channels",
    "api",
]
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'backend.urls'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS" , "").split(',')
CORS_ALLOW_CREDENTIALS = True
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
# JAZZMIN_SETTINGS = {
#     # Site branding
#     "site_title": "ProAdmin",
#     "site_header": "Professional Administration",
#     "site_brand": "ProAdmin",
#     "site_logo": None,  # Add your logo path here
#     "login_logo": None,  # Add your login logo path here
#     "login_logo_dark": None,
#     "site_logo_classes": "img-circle",
#     "site_icon": None,  # Add favicon path here
    
#     # Welcome text
#     "welcome_sign": "Welcome to Professional Admin Dashboard",
    
#     # Copyright
#     "copyright": "Your Company Ltd",
    
#     # Search model
#     "search_model": ["auth.User", "auth.Group"],
    
#     # User avatar
#     "user_avatar": None,
    
#     # Top Menu
#     "topmenu_links": [
#         {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
#         {"name": "Support", "url": "https://github.com/your-repo", "new_window": True},
#         {"model": "auth.User"},
#         {"app": "books"},
#     ],
    
#     # User menu on the top right
#     "usermenu_links": [
#         {"name": "Support", "url": "https://github.com/your-repo", "new_window": True},
#         {"model": "auth.user"}
#     ],
    
#     # Side Menu ordering
#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "hide_apps": [],
#     "hide_models": [],
    
#     # Custom links to append to app groups
#     "custom_links": {
#         "books": [{
#             "name": "Make Messages", 
#             "url": "make_messages", 
#             "icon": "fas fa-comments",
#             "permissions": ["books.view_book"]
#         }]
#     },
    
#     # Icons for side menu
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#     },
    
#     # Icons for models (use Font Awesome or similar)
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-circle",
    
#     # Related modal
#     "related_modal_active": False,
    
#     # Custom CSS/JS
#     "custom_css": None,  # Add this line
#     "custom_js": None,
    
#     # Show language chooser
#     "show_ui_builder": False,
    
#     # Changeform templates
#     "changeform_format": "horizontal_tabs",  # or "vertical_tabs", "collapsible", "carousel"
#     "changeform_format_overrides": {
#         "auth.user": "collapsible", 
#         "auth.group": "vertical_tabs"
#     },
    
#     # Language chooser
#     "language_chooser": False,
# }


# JAZZMIN_UI_TWEAKS = {
#     # Theme Selection
#     "theme": "cyborg",  # Modern dark theme (alternatives: "slate", "superhero", "darkly")
#     "dark_mode_theme": "cyborg",  # Consistent dark mode
    
#     # Typography
#     "navbar_small_text": False,
#     "footer_small_text": True,
#     "body_small_text": False,
#     "brand_small_text": False,
#     "brand_colour": False,
    
#     # Accent colors
#     "accent": "accent-primary",
    
#     # Navbar
#     "navbar": "navbar-dark",
#     "no_navbar_border": True,  # Cleaner look
#     "navbar_fixed": True,
    
#     # Layout
#     "layout_boxed": False,  # Full-width modern design
#     "footer_fixed": False,
    
#     # Sidebar
#     "sidebar_fixed": True,
#     "sidebar": "sidebar-dark-primary",
#     "sidebar_nav_small_text": False,  # Better readability
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": True,
#     "sidebar_nav_compact_style": False,  # More spacious
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": True,  # Modern flat design
    
#     # Button styling
#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     },
# }
# LOGIN_RIDERECT_URL = "/callback/"
SOCIALACCOUNT_STORE_TOKENS = True
